kind: pipeline
type: docker
name: build

steps:
  - name: docker
    image: plugins/docker
    settings:
      repo: jadiewadie/roundsquare
      username:
        from_secret: DOCKER_USERNAME
      password:
        from_secret: DOCKER_PASSWORD
      tags: latest
